### ISSUE TITLE
اضافه کردن ریالیتی به صورت چند دامنه

### ISSUE THREAD

**Issue by semsierra** [hiddify/Hiddify-Server#1011]
سلام. اگر امکانش باشه که بشه ریالیتی رو روی چند ساب دامنه به صورت جدا با SNIـهای مختلف کانفیگ کرد عالی میشه.

**Comment by xmohammad1** [comment]
دقیقا , مشکل این sni اینه که ممکنه اختلال بگیره روی یه اینترنت و بعدش بخوای عوض کنی کل کاربرا قطع میشن تا وقتی که کانفیگشونو بروز کنن ولی اگه چند sni باشه یکیم تغییر بدی مشکلی خاصی پیش نمیاد
