### ISSUE TITLE
مشکل اجرای پنل بر روی سرور های aeza

### ISSUE THREAD

**Issue by mdseven** [hiddify/Hiddify-Server#1046]
سلام
گویا پنل روی سرور هایی ک از سایت aeza.net هستن باز نمیشه
بعد از نصب لینک ورورد به پنل ارور 502 میده
پنلای دیگه مثل xui مشکلی ندارن فقط روی هیدیفای اینطوره
احتمالا دسترسی خاصی توی سرور نیاز داره یا پنل تغییراتی نیاز داره ممنون میشم بررسی کنید

**Comment by newwebform** [comment]
دقیقا همین مشکلا داره رو هرترنر اکیه روی این نصب نمیشه احتمالا یه سرویسی رو سرور کمه. این دیتا سنتر خوبیش ای پی تمیزشه ولی تو این چند روز که من گرفتم چند ساعتم قطعی داره.
