### ISSUE TITLE
مشکل در عدم قطع اتصال کاربر ورژن 7.0.9

### ISSUE THREAD

**Issue by realartin** [hiddify/Hiddify-Server#2781]
کاربری که ترافیک یا زمانش به اتمام رسیده ولی دامنه از پنل حذف شده همچنان متصل است !
هسته xray نصب تمیز بعد از ریبیلد سرور

**Comment by Goldencam** [comment]
اصلا حذف کاربر ظاهری هست و اصلا حذف نمیشه اکانت مادم العمر داره.
شما بیا uuid کاربر را کپی بردار کاربر حذف کن 
بعد برو کاربر جدید تعریف کن و حالا بیا uuid  کاربر جدید ادیت کن و اون کپی رو قرار بده 
خیلی شیک و مجلسی میگه تکراری هست و نمیزاره ثبت کنی
