### ISSUE TITLE
دامنه سازگار با REALITY نیست! 

### ISSUE THREAD

**Issue by m0x61h0x64i** [hiddify/Hiddify-Server#2803]
**Describe the bug**
اومدم دامنه برای ریالیتی پیدا کردم با این ویژگی ها
Protocol  TLS 1.3
Key exchange  X25519
Server signature  RSA-PSS with SHA-256
Cipher  AES_256_GCM

اما وقتی توی پنل اضافش میکنم میگه :

دامنه سازگار با REALITY نیست! 

مشکلش چیه؟!
**To Reproduce**

برید دامنه winscp.net رو به عنوان دامنه ریالیتی توی قسمت های دامنه بازگشتی ریالیتی و نام‌های سرور ریالیتی بزارید و  ذخیره و ارور رو ببینید

**Expected behavior**
ارور نده

**Screenshots**
![image](https://github.com/hiddify/hiddify-config/assets/109550653/bc004c27-5630-44ae-84ee-2814616377f4)
![image](https://github.com/hiddify/hiddify-config/assets/109550653/6d606490-2e84-42fb-b769-92f2b3ad3714)

**Desktop (please complete the following information):**
سیستم عامل سرور اوبونتو 20
کروم

**Comment by m0x31h0x64i** [comment]
یه نمونه دیگش
hetzner.com

**Comment by m0x31h0x64i** [comment]
دامنه هایی هم که اول ساب دامینشون تک حرفیه فکر میکنم ارور bad gateway میده مثل این
a.techresearchhub.com
