### ISSUE TITLE
Docker image runtime error

### ISSUE THREAD

**Issue by sohrabp72** [hiddify/Hiddify-Server#3087]
Tested on Ubuntu 20.04

root@Iran:~/hiddify/hiddify-config# docker compose up -d
[+] Running 1/1
! hiddify Warning 2.6s
[+] Building 1653.3s (8/10)
[+] Building 2624.9s (8/10)
[+] Building 2759.9s (11/11) FINISHED
=> [hiddify internal] load build definition from Dockerfile 0.1s
=> => transferring dockerfile: 609B 0.0s
=> [hiddify internal] load .dockerignore 0.1s
=> => transferring context: 59B 0.0s
=> [hiddify internal] load metadata for docker.io/library/ubuntu:22.04 2.1s
=> CACHED [hiddify 1/6] FROM docker.io/library/ubuntu:22.04@sha256:6120be6a2b7ce665d0cbddc3ce6eae60fe94637c6a66985312d1f02f63cc0bcd 0.0s
=> => resolve docker.io/library/ubuntu:22.04@sha256:6120be6a2b7ce665d0cbddc3ce6eae60fe94637c6a66985312d1f02f63cc0bcd 0.0s
=> [hiddify internal] load build context 1.4s
=> => transferring context: 80.04MB 1.3s
=> [hiddify 2/6] RUN apt-get update && apt-get install -y dialog apt-utils curl sudo systemd python2 xxd lsof 267.0s
=> [hiddify 3/6] WORKDIR /opt/hiddify-config/ 0.1s
=> [hiddify 4/6] COPY . . 0.5s
=> [hiddify 5/6] RUN bash install.sh install-docker 2471.8s
=> [hiddify 6/6] RUN curl -L https://raw.githubusercontent.com/gdraheim/docker-systemctl-replacement/master/files/docker/systemctl.py 3.6s
=> [hiddify] exporting to image 14.6s
=> => exporting layers 14.6s
=> => writing image sha256:0a0a425413b50b6df19b222fc86c19810c41d233060f53e163fcbaa6a4f6d499 0.0s
=> => naming to docker.io/library/hiddify 0.0s
[+] Running 1/2
✔ Network hiddify-config_default Created 0.1s
⠿ Container hiddify-config-hiddify-1 Starting 0.8s
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/root/hiddify/hiddify-config/hiddify-panel/hiddifypanel.db" to rootfs at "/opt/hiddify-config/hiddify-panel/hiddifypanel.db": mount /root/hiddify/hiddify-config/hiddify-panel/hiddifypanel.db:/opt/hiddify-config/hiddify-panel/hiddifypanel.db (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

**Comment by ad2248** [comment]
This problem I presume is due to a file creation error. A file should have been created but instead a directory was created. So, we just need to manually create the file in advance, and the operation to create the directory will naturally fail when the container starts, and the problem is solved.
`touch /opt/hiddify-config/hiddify-panel/hiddifypanel.db`
