### ISSUE TITLE
Reality "You have already used this Domain in: Domain Fronting"

### ISSUE THREAD

**Issue by someonemax** [hiddify/Hiddify-Server#3134]
وقتی میخوام دامین ریلیتی رو تغییر بدم این ارور رو میده. و چون قسمت Domain Fronting هم از بخش تنظیمات کلا حذف شده در ورژن جدید امکان تغییر دامین Domain Fronting هم وجود نداره.

**Comment by alisadri5890** [comment]
منم همین مشکل رو دارم
