### ISSUE TITLE
Proxy Configuration

### ISSUE THREAD

**Issue by Phantom1X** [hiddify/Hiddify-Server#3256]
**Describe the bug**
Proxy rule profiles do not modify GEOIP country and region top-level domains based on the Hiddify panel region.

**Expected behavior**
Proxy rule profiles modify GEOIP country and region top-level domains based on the Hiddify panel area.

**Screenshots**
![image](https://github.com/hiddify/Hiddify-Server/assets/38597174/ffb25f2d-13bf-4784-aecb-e8684ad5fc94)

**Comment by Eslender73** [comment]
Thank you for your report
