### ISSUE TITLE
Submit button behavior 

### ISSUE THREAD

**Issue by 12121af** [hiddify/Hiddify-Server#3258]
Bug Description:
When attempting to modify settings within the admin panel, the "submit" button does not function as expected.

Steps to Reproduce:

Navigate to the admin panel.
Click on the relevant section to modify settings.
Attempt to submit the changes.
Expected Behavior:
The changes made in the admin panel should be saved when the "submit" button is clicked.

Additional Context:
This issue is observed across various web browsers on macOS.

**Comment by zZedix** [comment]
you have to change the ShadowTLS , FakeTLS and Decoy Website Domains it Would Fix The Problem
and remember you have to always do an apply configs after any changes in your setting
