### ISSUE TITLE
Api

### ISSUE THREAD

**Issue by xmohammad1** [hiddify/Hiddify-Server#3260]
یه خسته نباشید به همه تیم هیدیفای، ممنون بابت زحماتتون
اگه امکانش هست api حذف و یا فعال غیرفعال کردن کاربر رو هم اضافه کنید ، همچنین وقتی وضعیت کاربر رو میگیریم یه بخشی نشون بده که این کاربر فعال هست یا خیر
با تشکر فراوان

**Comment by lymanjre** [comment]
این ایشو قبلا ثبت شده و در حال پیگیری است. بنابراین بسته میشود.
