### ISSUE TITLE
Concurrent Connections

### ISSUE THREAD

**Issue by blue-farid** [hiddify/Hiddify-Server#3261]
I'm always frustrated when I have a high number of concurrent users accessing my application, and I notice that it struggles to handle the load efficiently. Currently, the application seems to have a limitation on the number of concurrent connections it can handle, which results in slow response times and potential timeouts for users.

I would like to request the implementation of a feature that allows the application to handle a significantly higher number of concurrent connections more efficiently. This improvement would ensure that the application can scale and handle the load gracefully, without compromising user experience.

**Comment by Sensetize** [comment]
Device limit on one key would be great to reduce number of abusers and server overload

**Comment by zZedix** [comment]
its not possible on hiddify panel yet

**Comment by zZedix** [comment]
its not possible on hiddify panel yet

**Comment by blue-farid** [comment]
> its not possible on hiddify panel yet

Although I am aware that it is currently not possible, I would like to make this an open issue, inviting individuals to submit pull requests for its implementation, including the possibility of doing it myself.

**Comment by naymintun800** [comment]
any solution on this?

**Comment by sariyan-0** [comment]
yep I dont think it has that
