### ISSUE TITLE
Add Tuic and Hysteria again

### ISSUE THREAD

**Issue by primemb** [hiddify/Hiddify-Server#3263]
Previously, there was an implementation for Tuic, but it was deleted, possibly due to malfunction. However, the new versions of both Tuic and Hysteria protocols seem to be working, so can we bring back the implementation?

**Comment by zZedix** [comment]
in the next version tuic and hysteria will be available on hiddify

**Comment by omidshojaee** [comment]
Sorry to bring back this. I'm on v8.8.2 and still can't find any trace of Hysteria2?
