### ISSUE TITLE
Improve server dashboard gauges / counters

### ISSUE THREAD

**Issue by fakoor** [hiddify/Hiddify-Server#3264]
**Is your feature request related to a problem? Please describe.**
No problem. Improve server dashboard by a number of changes:

**Describe the solution you'd like**

- Please move the real-time user counter (a.k.a last 5 minutes) to the top of the list to maintain a chronological order (last 5min, today, yesterday, last month, etc.)
- Also please add a few other casual counters expected for such panels as well if possible:

    1.  Swap file usage
    2. Number of active TCP/UDP sockets on the server
    3. System uptime

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by Eslender73** [comment]
We have seen your suggestion and will implement it if possible. 
Thank you
