### ISSUE TITLE
عدم اجرای کانفیگها پس از ورژن 7.2 در حالتی که دامنه ریلی با تانل معکوس اس اس اچ بالا می آید

### ISSUE THREAD

**Issue by HadiTak** [hiddify/Hiddify-Server#3265]
قبلا در ورژن 7 پس از زدن reverse ssh tunnel بین سرور خارج به داخل، تمام کانفیگها کار میکردند. اما در ورژن 8 دیگر هیچ کدام از کانفیگها کار نمیکنند. تونل بطور کامل برقرار میشود و دامنه relay هم کار میکند اما کانفیگها کار نمیکنند. همینک نیز تنها با دانگرید به ورژن 7.2 کانفیگها کار میکنند.

**Comment by zZedix** [comment]
منظورتون از تانل معکوس همون reverse Tls tunnel ؟

**Comment by HadiTak** [comment]
> منظورتون از تانل معکوس همون reverse Tls tunnel ؟

نه من reverse ssh tunnel میزنم. اونی که میفرمایید تازه مد شده ولی من قبلا با هیدیفای هم reverse ssh میزدن

**Comment by Eslender73** [comment]
> > منظورتون از تانل معکوس همون reverse Tls tunnel ؟
> 
> 
> 
> نه من reverse ssh tunnel میزنم. اونی که میفرمایید تازه مد شده ولی من قبلا با هیدیفای هم reverse ssh میزدم

دوست عزیز reverse ssh tunnel با سرویس haproxy از قدیم تداخل داشت و ویشنهاد نویشود

**Comment by HadiTak** [comment]
ولی در حال حاضر روی ورژن ۷.۲ بسیار عالی، با سرعت خوب و بدون مشکل هم کار میکنه

**Comment by Eslender73** [comment]
این قضیه رو داخل نسخه دولوپ چک کردید؟

**Comment by HadiTak** [comment]
بلی حدود 2 هفته پیش بود تست کردم جواب نداد

**Comment by Eslender73** [comment]
تلگرام به این ایدی پیام بده
@Slender73
