### ISSUE TITLE
connect ssh tunnel

### ISSUE THREAD

**Issue by Aronablade** [hiddify/Hiddify-Server#3266]
hi , i have installed hidify and it works fine on xray configs , i saw ssh tunnel option as well , how can i connect to ssh tunnel ? i can find the port option but how can i set a username and password for users to connect with ssh tunnel ?

**Comment by zZedix** [comment]
for using ssh config you have to use Sing Box app or hiddify Next client
in the user page there is a SSH config which you can use on those clients
