### ISSUE TITLE
مشکل نمایش ترجمه متن‌ها در پنل

### ISSUE THREAD

**Issue by aliwebsd** [hiddify/Hiddify-Server#3269]
سلام وقت بخیر
چرا پنل روی هر زبانی میذارم درست نشون نمیده؟ خود ترنسلیت‌ها رو انگار داره نشون میده!

<img width="1600" alt="image" src="https://github.com/hiddify/Hiddify-Server/assets/13856958/b8db36a8-25d7-4705-8adf-85c08ebfd420">

**Comment by AARRZZNN** [comment]
دقیقا منم همین مشکل رو دارم . همه چی نامرتب هست

**Comment by Amir-a-Salmani** [comment]
منم این مشکل رو دارم.

**Comment by hiddify-com** [comment]
fixed in 8.6.4
