### ISSUE TITLE
مشکل نصب touch: cannot touch '/root/.acme.sh/http.header': No such file or directory

### ISSUE THREAD

**Issue by miladfff** [hiddify/Hiddify-Server#3270]
گزارش باگ
دیتاسرور: bitcammnder
 لوکیشن سرور :ترکیه
سیستم عامل: Ubuntu22-64
مشکل : موقع نصب ارور میخوره و چندبار تاحالا کل سیستم عامل رو از اول نصب کردم و کل اطلاعات رو‌پاک کردم ولی بازهم نصب نمیشه
تازه سرور رو خرید دستور نصب سریع رو زدم  از همین دیتا سرور لوکیشن کانادا هم دارم بدون مشکل نصب شد

[Med Oct: 4 14:10:30 +0330 2023] Installing cron job
[Wed Oct 4 14:10:30 +0330 2023] Good, bash is found, so change the shebang to use bash as preferred
[wed Oct 4 14:10:31 +0330 2023] OK
[wed Oct 4 14:10:31 +0330 2023] Install success!
touch: cannot touch '/root/.acme.sh/http.header': No such file-or directory
[Wed Oct 4 14:13:36 +0330 2023] Please refer to https://cuzl.haxx.se/libcurl/c/libcurl: -errors html for error code: 35
[Wed Oct 4 14:13:36 +0330 2023] Can not init api for: https://acme zerossl.
[Wed Oct 4. 14:13:36 +0330 2023] Sleep 10 and retry.
com/ v2/DV90.
touch: cannot touch '/root/.acme.sh/http.header': No such file or directory
Wed Oct .4 14:16:48 +0330 2023] please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 35
[Wed Oct 4 14:16:48 +0330 2023] Can not init api for: https://acme.zerossl.com/v2/Dv90
[Wed Oct 4 14:16:48 +0330 2023] sleep 10 and retry.
touch: cannot touch '/root/.acme.sh/http.header': No such file or directory
Wed Oct 4 14:20:03 +0330 2023] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 35
[Wed Oct
4 14:20:03 +0330 2023] Can not init api for: https://acme.zerossl.com/v2/Dv90.
[Wed Oct 4 14:20:03 +0330 2023] sleep 10 and retry.
touch: cannot touch '/root/.acme.sh/http.header': No such file or directory
[Wed Oct 4 14:23:15 +0330 2023] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 35
[Wed Oct 4 14:23:15 +0330 2023] Can not init api for: https://acme.zerossl.com/¥2/Dv90.
[Wed Oct 4 14:23:15 +0330 2023] sleep 10 and retry.
touch: cannot touch '/root/.acme.sh/http.header': No such file or directory
[Wed Oct 4 14:26:28 +0330 2023] Please refer to https://curl.haxx.se/libcur1/c/libcurl-errors.html for error code: 35
[Wed Oct 4 14:26:28 +0330 2023] Can not init api for: https://acme.zerossl.com/v2/Dv90.
[Wed Oct 4 14:26:28 +0330 2023] sleep 10 and retry.
touch: cannot touch '/root/.acme.sh/http.header': No such file or directory
4 14:29:40 +0330 2023] Please refer to https://curl.haxx.se/libcurl/c/libcurl-errors.html for error code: 35
[Wed Oct 4 14:29:40 +0330 2023] Can not init api for: https://acme.zerossl.com/v2/Dv90.
[Med Oct
[Wed Oct 4 14:29:40 +0330 2023] sleep 10 and retry.

**Comment by Eslender73** [comment]
در نسخه اخر هم بی زحمت تست کنید 
حتما قبلش سیستم عامل رو ریبیلد کنید
حتما dns سرور 1.1.1.1 قرار دهید قبل نصب
حتما ip6 سرور رو غیر فعال کنید قبل نصب
درصورت تکرار شدن مشکل همینجا اعلام کنید بررسی میشود
