### ISSUE TITLE
اضافه نشدن کانفیگ vmess به نرم افزارها

### ISSUE THREAD

**Issue by asghari111** [hiddify/Hiddify-Server#3271]
گزارش باگ
دیتاسرور: هتزنر
لوکیشن سرور : المان
سیستم عامل: Ubuntu22
مشکل : کانفیگ‌های vmess چه از طریق اسکن QR چه به صورت کپی کردن کد، داخل هیچ نرم افزاری اضافه نمیشه
ممنون میشم این مورد پیگیری بشه

**Comment by Eslender73** [comment]
لینک vmess مشکل دارد دولوپر ها در ورژن های بعدی درست خواهند کرد.میتوانید از لینک ساب استفاده کنید 
با تشکر از گزارش شما
