### ISSUE TITLE
مشکل زبان پنل

### ISSUE THREAD

**Issue by ea1234567** [hiddify/Hiddify-Server#3272]
آپدیت 8.6.3 رو الان روی یک سرور خام نصب کردم (اوبونتو 22)
1-زبان پنل فارسی نمیشه کلا
2-زبان انگلیسی هم کلا مشکل داره و منو ها درب و داغون شدن توی زبان انگلیسی

**Comment by simboos** [comment]
برای منم دقیقا همین مشکل رو داره

**Comment by hiddify-com** [comment]
fixed in 8.6.4
