### ISSUE TITLE
warp +

### ISSUE THREAD

**Issue by sepahdalton** [hiddify/Hiddify-Server#3273]
وارپ تز نسخه ۷.۰۲ به بعد دیگه بدرستی کار نمیکنه
توی نسخه 8.6.3 هرکاری کردم که بشه ترافیک کلی از وارپ رد بشه نشد که نشد پنل تو این ضمینه باگ داره از لایسنس کلید ها مطمن هستم چون بصورت اختصاصی تهیه کردم
لطفا مشکل وارپ در پنل حل کنید
سپاس فراوان

**Comment by gis200584** [comment]
سلام و دست مریزاد وارپ از نسخه ۷ به بعد به درستی کار نمی کنه توی سرچ ها هم به مشکل خورده باید فیلتر شکن رو قطع کنی وگر نه ارور کپچای گوگل نمی زاره ادامه بدید 
تو نسخه ۷ همه چی عالی کار می کرد خواهشا این مشکل رو برطرف کنید بسیار ازار دهنده س

**Comment by Eslender73** [comment]
خیلی ممنون از گذارشتون 
دولوپر های عزیزمون در جریان این مشکل هستن در حال عیب یابی و ارائه نسخه بدون ایراد هستن
بزودی مشکل برطرف خواهد شد
