### ISSUE TITLE
مشکل در ایجاد ادمین از طریق api 

### ISSUE THREAD

**Issue by nwhdesign** [hiddify/Hiddify-Server#3274]
سلام به همه عزیزان هیدیفای دوستان من می‌خوام از طریق api ادمین بسازم ارور میده لطف میکنید بررسی کنید 
The browser ( or proxy ) sent a request that this server could not understand

**Comment by Eslender73** [comment]
ممنون از گزارشتون

**Comment by nwhdesign** [comment]
ممنون بابت تیم خوبتون مشکل برطرف شد ای کاش مکان حذف و یا غیر فعال کردن کاربر هم اضافه کنید
