### ISSUE TITLE
باگ پنل

### ISSUE THREAD

**Issue by changecoin938** [hiddify/Hiddify-Server#3275]
سلام 
یه سری مشکلات دیدم 
۱-بلاک سایت های ایرانی فقط در مرحله نصب اگر خاموش کنید یا روشن تا اخر همونه و وقتی بخواین تغییر بدین هیچ تغییری نمیکنه
۲- ای پی وارپ تغییر نمیکنه
۳- وارپ کار نمیکنه 
۴-پنل زبانش کلا به هم ریخته

**Comment by Eslender73** [comment]
برای زبان پنل لطفا بروزرسانی کنید پنل را
مشکل وارپ در جریان هستیم در دست اقدام برای رفع مشکل هست
ممنون از گزارشون
