### ISSUE TITLE
مصرف 1.7گیگ رم توسط پروسس سینگ باکس

### ISSUE THREAD

**Issue by amin2plus** [hiddify/Hiddify-Server#3276]
**Describe the bug**

نسخه پنل استیبل 8.6.2 و 8.6.3
پروسس singbox حدود 1.7 گیگ رم میخواد! و چون ریسورس سرور کم میاره ، همه چیز قطع میشه
(حتی ssh هم نمیشه زد به سرور و باید از هاست بزنم سرور ریبوت بشه)
این اتفاق حدودا روزی یک بار اتفاق میافته
 
هسته پنل سینگ باکس هست
کانفیگ هایی که استفاده میشوند فقط trojan/vless/reality فعال هستند و از تنظیمات باقی نوع پروکسی ها خاموش هستند
کاربران سرور زیاد نیستند زیر 30گیگ روزانه ترافیک سرور هست

**Expected behavior**

خیلی زمان پیش مصرف رم روی 500 مگ اپتیمایز کردین و تکنیکالی نباید مصرف به یک گیگ برسه ولی زمانی که سرور از کار میافته و vnc از هاست میگیرم لاگ میندازه که پروسس singbox حدود 1.7 گیگ رم میخواسته
اگر لطف کنید پروسس singbox رو هم چک کنید و آپتیمایز کنید اگر امکانش باشه ممنون میشم

**Screenshots**

![image](https://github.com/hiddify/Hiddify-Server/assets/31206022/c03c99ce-7426-4c15-a913-39a87be16465)

**additional**

هاست هایی مثل hetzner و ovh  ازین اتفاق ها بیافته ممکنه سرور رو pause یا خاموش کنن، 
یا حتی هاست هایی که oversell میکنند هم ازین اتفاق ها روزی یک بار هم بیافته VM کاربر رو ممکنه ریبوت کنند

**Comment by amin2plus** [comment]
more screenshots, this time it happened when i hit the update button on the web panel settings

![image](https://github.com/hiddify/Hiddify-Server/assets/31206022/5b65593f-edc6-4d62-b302-2c5eb936972b)

**Comment by Eslender73** [comment]
لطفا ذکر کنید دیتاسنتر خایی که همچین مشکلی دارن چی هستن
اخرین ورژن پنل رو نصب و تست بفرمایید
سرور با وارپ خاموش و روشن تست شود 
گذارشتون رو همینجا اعلام کنید 

با تشکر

**Comment by Eslender73** [comment]
ممنون از کمکتون
بی زحمت کامل چندین روز تست کنید اگر مشکلی بود به صورت کامل و طبق فرمت گزارش مشکل ایشو بزنید

**Comment by amin2plus** [comment]
توی پنل ورژن 8.6.4 هم مجدد این مشکل پیش امد
وارپ روشن
هسته سینگ باکس
کانفیگ هایی که استفاده میشه WS trojan/vless CDN و خیلی کم reality
استفاده از سرور در روز حدود 30 گیگ هست
چیزی که VNC از هاست نشون میده:
![image](https://github.com/hiddify/Hiddify-Server/assets/31206022/e5f75936-9b42-450a-a1d6-075b3b7a381e)

**Comment by lymanjre** [comment]
این مورد برای بررسی و رفع مشکل منتقل میشود. ایشو فعلا بسته میشود

**Comment by amin2plus** [comment]
update:
v8.6.6
تا 8 کاربر همزمان و نهایتا 25 گیگ استفاده در روز مصرف کم شده ولی همچنان مشکل باقیست، ایندفعه چند روز طول کشید تا مشکل پیش بیاد ولی
![image](https://github.com/hiddify/Hiddify-Server/assets/31206022/ff952763-0323-474f-8426-578fbbecbb52)
