### ISSUE TITLE
آپدیت پنل به ورژن جدید

### ISSUE THREAD

**Issue by alirezarah** [hiddify/Hiddify-Server#3277]
سلام و خسته نباشید
پنل هدیفای یه پیغام قرمز میده از قسمت ادمین اپدیت کنید ولی وقتی آپدیت میکنم پنل ورژنش تغییر نمیکنه و همون ورژن قبلیه و دوباره همان پیغام میاد

**Comment by Eslender73** [comment]
برای اپدیت در این جور مواقع باید این دستور را اجرا کنید.درصورت درست نشدن مشکلتون از سرور بکاپ بگیرید و ریبیلد انجام دهید 
sudo rm -rf /usr/lib/python3/dist-packages/OpenSSL
sudo pip3 install pyopenssl
sudo pip3 install pyopenssl --upgrade
echo "nameserver 1.1.1.1" >/etc/resolv.conf  &&sysctl -w net.ipv6.conf.all.disable_ipv6=1 &&/opt/hiddify-config/update.sh release
