### ISSUE TITLE
پروکسی

### ISSUE THREAD

**Issue by idevyami** [hiddify/Hiddify-Server#3280]
به نظرم اگه گزینه ای اضافه بشه که بتونیم برای هر دامنه یه پروکسی جدا انتخاب کنیم خیلی خوب میشه چون الان من مثلا دوتا cdn دارم یکی کلود فلر یکی آروان بعد آروانم فقط با http خوب کار میکنه ولی کلاد فلرم با tls ها حالا من بخوام اینارو فعال کنم وقتی بخوام ساب لینک بدم به کسی بیشتر از 10 تا کانفیگ بالا میاد براس که این خیلی گیج کنندست لطفاً این گزینه رو اضافه کنید به پنل خیلی کمک میکنه

**Comment by zZedix** [comment]
دردست بررسی هست
