### ISSUE TITLE
مشکل نشون ندادن ورژن پنل

### ISSUE THREAD

**Issue by ea1234567** [hiddify/Hiddify-Server#3283]
سلام خدمت تیم دلسوز و زحمتکش هیدیفای
ورژن پنل و کانفیگ داخل منوی SSH بیشتر از یک ماهه که نشون داده نمیشه
بارها داخل تاپیک مخصوص تلگرام گزارش دادم این باگ رو،ولی بررسی نمیشه اصلا
آدم اینجوری از گزارش باگ دلسرد میشه
ممنون میشم بررسی کنید،سوادم نمیرسه ولی احساس میکنم رفع این باگ از لحاظ فنی باید برای شما مثل آب خوردن باشه چون باگ پیچیده ای نیست
شما باگ های پیچیده تر از این رو حل کردید قبلا
اسکرین شات:

![Untitled](https://github.com/hiddify/Hiddify-Server/assets/40317198/49988e12-e8d8-4b63-832f-88c73191b1f0)

**Comment by zZedix** [comment]
بررسی میشه
