### ISSUE TITLE
اضاقه شدن اسم کاربر روی لینک trojanیا

### ISSUE THREAD

**Issue by jadopcb** [hiddify/Hiddify-Server#3287]
سلام 
خسته نباشید و تشکر

بشه که اسم کاربر
 روی لینک تروجان
اضافه بشه -

که امکان تمدید لینک راحتر باشه 
نیاز به چک کردن کل لینک نباشیم
تشکر

**Comment by Eslender73** [comment]
بعید میدونم این قضیه تو لیست بره چون نقص از سمت نرمافزار میباشد نه از سمت پنل
برنامه نویسان عزیز سعی کردن یه کار حرفه ای جدایه از کارای دیگه داشته باشن 
این نام کاربر رو نرمافزار باید تشخیص بده خودش بنویسه بروی اسم اشتراک
اگر داخل تروجان هم نوشته باشه دو قسمت نام کاربر دیده میشه
میتوانید با مکاتبه با پشتیبانی نرمافزار هاتون درخواست خواندن نام از هدر و انتقال ان به نام کاربر در نرمافزار اقدام کنید
حتی میتوانید زمان بروز رسانی لینک اشتراک را هم از هدر بردارند نرمافزار ها

**Comment by jadopcb** [comment]
---
این نام کاربر رو نرمافزار باید تشخیص بده خودش بنویسه بروی اسم اشتراک
اگر داخل تروجان هم نوشته باشه دو قسمت نام کاربر دیده میشه
---
کار شما که خاص و حرفه ای -- تشکر
جای هیچ بحثی نیست از کیفت کارتون
--------
متاسفانه نرم افزار قابلیت ندارن جز یکی 

دوجا دیده بشه مشکلی نداره

محدود به استفاده از یک ترم افزار نباشیم
چون بعضی نرم افزار کارایی لازم ندارن

اسم ی که برای اشتراک مشخص بشه 
اونجام مشخص بشه
 بعضی دوستان گفتن قبلا بوده 
بعد حذف شده- چه بد-

بررسی کنین ممنون میشم 
کارساده تر میکنه برای تشخیص اشتراک
برای تمدید

تشکر
