### ISSUE TITLE
افزودن امکان لیست بندی

### ISSUE THREAD

**Issue by alifarnam1379** [hiddify/Hiddify-Server#3289]
با سلام وقت بخیر
لطفا امکان تغییر لیست بندی و‌جایگاه دامنه هارو هم اضافه کنید که بشه ترتیب بعضی دامنه هارو تغییر داد در حال حاضر برای تغییر جایگاه دامنه ها باید دامنه هارو حذف کنم و مجدد به ترتیب دلخواه اضافه کنم
ممنون میشم این مورد رو هم اضافه کنید
با تشکر

**Comment by lymanjre** [comment]
امکان ایجاد قابلیت بررسی میشود
