### ISSUE TITLE
کانفیگ ssh

### ISSUE THREAD

**Issue by harnid** [hiddify/Hiddify-Server#3291]
سلام
کانفیگ ssh برای یوزر هایی که قبل از اضاف شدن این پروتکل به پنل، پنل کاربری داشتن کار نمیکنه و توی اپ نکست ارور failed handshake میده ولی یوزرای جدید مشکلی نداره کانفیگشون
پ.ن: خودم امتحان کردم کانفیگشونو

**Comment by lymanjre** [comment]
سلام. مشکل در حال بررسی است. لطفا شکیبا باشید تا باگ رفع بشه
