### ISSUE TITLE
مشکل برقرار نشدن ارتباط با برخی از ارایه دهندگان vps

### ISSUE THREAD

**Issue by 0xShervin** [hiddify/Hiddify-Server#3293]
این پنل یکی از راحت ترین پنل ها و سریع‌ترین‌ها در نزد پنل های دیگری است که تا به حال استفاده کردم.
مشکلی گاهی اوقات با این پنل ایجاد میشود این است که در برخی از VPS ها همچون hostinger کانفیگ های مختلف را امتحان کرده و از هیچ کدام هیچ جوابی در برخی از ارایه دهندگان اینترنت (مخصوصا مخابرات) دریافت نمیکنم. من این پنل را در یکی از سرویس ها نصب کردم و بر روی همه ISP ها جواب میداد ولی برای من عجیب بود که روی hostinger که معروف هم است جوابی دریافت نمیکنم. ممنون میشم اگر به من کمکی کنید.

**Comment by Eslender73** [comment]
دوست عزیز ممنون از گزارشتون ولی کار نکردن سرویس بروی یک isp خاص مربوط میشه به کویف بودن ایپی در اون isp و یا استفاده از sni نامناسب
این قضیه ربطی به پنل نداره

**Comment by zeinali66** [comment]
سلام. من روی آمازون سرویس دارم. هر دو روز دارم آی‌پی عوض میکنم. ریالیتی ها از کار میافتد، لینک های ساب که مستقیم وصله قطع میشه. انگار آی‌پی لو میره. 
روی زیتل اکیه ولی روی اینترنت همراه سه تا اپراتور بلاک میشه. 
( من کارم شبکه است، تمام آموزش هاتون هم دیدم، خیالم راحته کانفیگ های پنل اکیه، چون 7 ماهی بدون دردسر وصل بودم.)

**Comment by amin2plus** [comment]
> سلام. من روی آمازون سرویس دارم. هر دو روز دارم آی‌پی عوض میکنم. ریالیتی ها از کار میافتد، لینک های ساب که مستقیم وصله قطع میشه. انگار آی‌پی لو میره. روی زیتل اکیه ولی روی اینترنت همراه سه تا اپراتور بلاک میشه. ( من کارم شبکه است، تمام آموزش هاتون هم دیدم، خیالم راحته کانفیگ های پنل اکیه، چون 7 ماهی بدون دردسر وصل بودم.)

کانفیگ ریالیتی که از مدل کانفیگ های direct هست و IP سرور کاملا معلوم هست! ریالیتی سعی میکنه فیلترینگ رو گول بزنه ولی وقتی استفاده زیاد باشه و کوچکترین نگاهی به استفاده بشه خیلی راحت اون IP فیلتر میشه، و اینکه با استفاده اون IP فیلتر بشه خیلی منطقی هست! 
من یک مورد داشتم سروری که همون روز امده بود بالا با دانلود یک فایل 6 گیگی سر 3ومین گیگ روی نت مخابرات IP سرور فیلتر شد!
میتونی از روش های CDN استفاده کنی که IP سرور پیش CDN هست و در بدترین حالت دامنه و زیردامنه بلاک میشه، "البته CDN ایرانی باشه فرق میکنه مسئله" و دیگه IP های هاست رو هم کثیف نمیکنی!! چند ماه بیشتر نگذشته و کلی کار داره تا تکمیل بشه و امیدوارانه یک روزی از CDNهم پشتیبانی کنه.

**Comment by Eslender73** [comment]
سعی کنید ایپیتون رو المی تست نکنید با کانفیگ های تابلو که سریع شناسایی میشن
پنل رو راهاندازی کردید فقط از کانفیگی استفاده کنید که امنیت بالاتری داره.
از دیتا سنتر شناخته نشده و sni گمنام استفاده کنید تا دیرتر شناسایی بشید

با تشکر
