### ISSUE TITLE
داون شدن سرور

### ISSUE THREAD

**Issue by changecoin938** [hiddify/Hiddify-Server#3297]
با سلام و خسته نباشید خدمت تیم هیدیفای عزیز 
سرور وقتی تعداد بالا یوزر میره روش سرور از دسترس خارج میشه 
من کافکا رو بررسی کردم وقتی اینجوری میشه خودش خودکار اضافه میکنه که به نظرم حیفه به هیدیفای همچین اپشنی اضافه نشه

**Comment by amin2plus** [comment]
منم همچین مشکلی دارم ولی کاربرام کمن، میتونی چک کنی که پروسس singbox بوده که رم زیاد مصرف کرده و دان شده سرور؟
https://github.com/hiddify/Hiddify-Server/issues/3276

**Comment by lymanjre** [comment]
این مشکل قبلا گزارش شده و تکراری است. بنابراین ایشو شما بسته میشود و مورد از طریق ایشوی قبلی در دست پیگیری است.
