### ISSUE TITLE
👁️‍🗨️ نمایش حجم و تاریخ انقضا در کانفیگ ها

### ISSUE THREAD

**Issue by mrsajjad2** [hiddify/Hiddify-Server#3299]
سلام و خسته نباشید.
کابرای زیاد درخواست داشتن که یوزرنیم کاربر دا خل کانفیگ فیک بیاد
trojan://1@{{fake_ip_for_sub_link}}?sni=fake_ip_for_sub_link&security=tls#{{user.current_usage_GB|round(3)}}/{{user.usage_limit_GB}}GB_Remain:{{expire_days}}days 
آیا امکانش هست به طور موقت تغییر داد به این شکل؟
trojan://1@{{user.name}}?sni=fake_ip_for_sub_link&security=tls#{{user.current_usage_GB|round(3)}}/{{user.usage_limit_GB}}GB_Remain:{{expire_days}}days 

برای 
trojan://1@{{fake_ip_for_sub_link}}#Package_Ended/{{user.name}}
اگر امکانش باشه تغییر داد؟

**Comment by lymanjre** [comment]
این ایشو برای بررسی منتقل شد. فعلا بسته میشود

**Comment by 1159548668** [comment]
****

**Comment by nazimomeni347-lgtm** [comment]
{"remarks":"⚡🚀 Vodcez / Vpn-98_7292016243_625-20.00GB📊","log":{"loglevel":"warning"},"inbounds":[{"tag":"socks","port":10808,"protocol":"socks","settings":{"auth":"noauth","udp":true,"userLevel":8},"sniffing":{"enabled":true,"destOverride":["http","tls"],"routeOnly":false}}],"outbounds":[{"tag":"proxy","protocol":"vless","settings":{"vnext":[{"address":"arvancloud.ir","port":80,"users":[{"id":"2398af60-5c04-471b-95c8-fcacd811d7f1","level":8,"encryption":"none"}]}]},"streamSettings":{"network":"ws","wsSettings":{"path":"/","headers":{"Host":"a.wpax.ir"}}},"mux":{"enabled":false,"concurrency":-1,"xudpConcurrency":8,"xudpProxyUDP443":""}},{"tag":"direct","protocol":"freedom","settings":{"domainStrategy":"UseIP"},"mux":{"enabled":false,"concurrency":8,"xudpConcurrency":8,"xudpProxyUDP443":""}},{"tag":"block","protocol":"blackhole","settings":{"response":{"type":"http"}},"mux":{"enabled":false,"concurrency":8,"xudpConcurrency":8,"xudpProxyUDP443":""}}],"dns":{"servers":["1.1.1.1"],"hosts":{"domain:googleapis.cn":"googleapis.com","dns.alidns.com":["223.5.5.5","223.6.6.6","2400:3200::1","2400:3200:baba::1"],"one.one.one.one":["1.1.1.1","1.0.0.1","2606:4700:4700::1111","2606:4700:4700::1001"],"dot.pub":["1.12.12.12","120.53.53.53"],"dns.google":["8.8.8.8","8.8.4.4","2001:4860:4860::8888","2001:4860:4860::8844"],"dns.quad9.net":["9.9.9.9","149.112.112.112","2620:fe::fe","2620:fe::9"],"common.dot.dns.yandex.net":["77.88.8.8","77.88.8.1","2a02:6b8::feed:0ff","2a02:6b8:0:1::feed:0ff"]}},"routing":{"domainStrategy":"IPIfNonMatch","rules":[{"type":"field","ip":["1.1.1.1"],"outboundTag":"proxy","port":"53"},{"type":"field","ip":["223.5.5.5"],"outboundTag":"direct","port":"53"}]}}

**Comment by gssgshsbsbdgdgd-sketch** [comment]
https://rw.veilora.net:8443/api/sub/G4HtjL8GS_6u9WoE
