### ISSUE TITLE
عدم اجرای کانفیگها روی دامنه ریلی در ورژن 8 در حالتی که تانل معکوس اس اس اچ زده میشود

### ISSUE THREAD

**Issue by HadiTak** [hiddify/Hiddify-Server#3300]
در ورژن 8 در تانلینگ به روش reverse ssh دیگر هیچ کانفیگی روی دامنه relay کار نمیکند اما هنوز هم با downgrade به ورژن 7.2 کانفیگ‌ها عالی کار میکنند. تانل به درستی برقرار شده و دامنه relay هم روی پنل کار میکند اما کانفیگها نه.

**Comment by lymanjre** [comment]
این ایشو برای بررسی منتقل شد. فعلا بسته میشود
