### ISSUE TITLE
وارپ 

### ISSUE THREAD

**Issue by Delta-Sheriff** [hiddify/Hiddify-Server#3301]
سلام لطفاً یه قابلیتی اضافه کنید بشه مثل پنل های مشابه ایرانی بتونیم یکسری دامنه و ساب دامنه هاش رو فقط از وارپ رد کنیم مثلاً وقتی وارپ روش میکنیم نمیشه باهاش گیم زد وقتیم خاموشه اسپاتیفای و موزیک اینستا کلا از دست میره

**Comment by lymanjre** [comment]
این مورد قبلا ثبت شده است و در دست بررسی است. بنابراین ایشو شما به دلیل تکراری بودن بسته میشود
