### ISSUE TITLE
مشکل SSH Proxy بعد از اپدیت

### ISSUE THREAD

**Issue by infinitaa** [hiddify/Hiddify-Server#3302]
با سلام و خسته نباشید واسه زحمات و کار بی نظیرتون
پروکسی SSH بعد از اپگرید کار نمیکنه توی SingBox، پروکسی های دیگه هم مث Reality توی پنل هستن
اما اگه پنل فرش نصل بشه، این مشکل وجود نداره
ممنون میشم راهنمایی کنین
لاگ مربوط به وصل نشدن توی SingBox هم توی عکس زیر هست
![photo_2023-09-17_00-54-20](https://github.com/hiddify/HiddifyPanel/assets/121110779/8e22675f-0b74-430f-be61-1d8dbb3e004b)

**Comment by lymanjre** [comment]
روی نسخه دولوپ تست کنید. این مشکل رفع شده است. ایشو بسته میشه اگه مشکل پابرجا بود اطلاع بدید
