### ISSUE TITLE
قطع نشدن اطلاع کاربران بعد انقضای اکانت

### ISSUE THREAD

**Issue by h7arash** [hiddify/Hiddify-Server#3303]
جدیدا متوجه شدم بعضی یوزر ها بعد از اتمام سرویس اتصالشون قطع نمیشه و چند روزی ادامه میدن استفاده از سرویس رو
تا زمانی که من متوجه بشم و اپدیت پنل یا "اعمال تغییرات" رو بزنم
کسی میدونه این مشکلات از چیه؟

**Comment by lymanjre** [comment]
این باگ روی نسخه ۸.۶ رفع شده. چک بکنید اگه همچنان این مشکل بود اطلاع بدید.

**Comment by mnj841** [comment]
سلام من ورژن 10 هستم ولی باز این مشکل هست
