### ISSUE TITLE
warp

### ISSUE THREAD

**Issue by saeeddarestany** [hiddify/Hiddify-Server#3304]
سلام . خیلی خوب میشه اگه داخل پنل بشه لیست سایت هایی که نیاز هست از وارپ رد بشه رو مشخص کرد  . الان خیلی کلی هست . مثلا من به شخصه نیاز ندارم گوگل از وارپ استفاده کنه و که باعث افت سرعت میشه و  ..... صرفا نیاز دارم spotify از وارپ رد بشه . اشخاص دیگه هم ممکن هست نیاز های متفاوت داشته باشند .
الان مجبور شدم کانفیگ routing رو ویرایش کنم و هرشب با کرون بعد از آپدیت پنل جایگزین کنم 
ممنون

**Comment by lymanjre** [comment]
این ایشو تکراری است و قبلا توسط دوست دیگری ثبت شده و در دست پیگیری است. بنابراین این ایشو بسته میشود. با سپاس از همراهی شما
