### ISSUE TITLE
مشکل سرویس در نسخه 8

### ISSUE THREAD

**Issue by navidonline** [hiddify/Hiddify-Server#3305]
سلام.ممنون بابت زحمت هاتون.

مشکلی از نسخه 8 به بعد بوجود آمده.
سرویس ایجاد کاربر جدید در هر حالتی خطای 500 با فرمت زیر میدهد:
`{
    "message": "Internal Server Error"
}`

کاربر ایجاد می شود ولی خطای 500 میدهد و کاربر حدود 1 دقیقه بعد فعال و قابل اتصال می شود.
POST /api/v1/user/

`{
    "uuid": "2bd86d07-e4b2-4659-8e05-6e35d3b9324343",
    "name": "test",
    "usage_limit_GB": 10,
    "package_days": 30,
    "added_by_uuid": "admin_id",
    "comment": null,
    "current_usage_GB":0
}`

مشکل دوم:
سرویس /GET   /api/v1/user  که لیست کاربران را برمی گرداند امکان فیلتر براساس uuid را ندارد

لطفا در صورت امکان این مشکل را بررسی و پاسخ دهید
متشکرم

**Comment by lymanjre** [comment]
این ایشو برای بررسی منتقل شد. فعلا بسته میشود
