### ISSUE TITLE
وارپ

### ISSUE THREAD

**Issue by mehrdadtopme** [hiddify/Hiddify-Server#3306]
چطور آیپی وارپ را تغییر دهید؟

سلام من طبق اموزش اومدم ای پی وارپ رو تغیر بدم که این پیغام رو میده و تغیر نمیکنه

--2023-10-10 18:10:35--  https://raw.githubusercontent.com/fscarmen/warp/main/api.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.109.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-10-10 18:10:35 ERROR 404: Not Found.

mv: cannot stat 'wgcf-account.toml': No such file or directory
bash: run.sh: No such file or directory

**Comment by mehrdadtopme** [comment]
https://github.com/hiddify/Hiddify-Server/wiki/%D8%A2%D9%85%D9%88%D8%B2%D8%B4-%D9%81%D8%B9%D8%A7%D9%84%E2%80%8C%D8%B3%D8%A7%D8%B2%DB%8C-%D9%88%D8%A7%D8%B1%D9%BE-%D8%AF%D8%B1-%D9%BE%D9%86%D9%84-%D9%87%DB%8C%D8%AF%DB%8C%D9%81%D8%A7%DB%8C#%DA%86%D8%B7%D9%88%D8%B1-%D8%A2%DB%8C%D9%BE%DB%8C-%D9%88%D8%A7%D8%B1%D9%BE-%D8%B1%D8%A7-%D8%AA%D8%BA%DB%8C%DB%8C%D8%B1-%D8%AF%D9%87%DB%8C%D8%AF

**Comment by lymanjre** [comment]
این ایشو برای بررسی منتقل شد. فعلا بسته میشود
