### ISSUE TITLE
باگ تعریف ادمین

### ISSUE THREAD

**Issue by nojhanac** [hiddify/Hiddify-Server#3309]
#باگ 
ورژن 8.6.6
موضوع:
هر ادمینی که تعریف میکنی اون ادمین هم میتونه یه ادمین با هر مقدار یوزر تعریف کنه
تورو خدا اینو رفع کنید
![IMG_20231011_112234_801](https://github.com/hiddify/Hiddify-Server/assets/141612269/98338302-6c43-443c-b647-cf9a4465dca0)

**Comment by lymanjre** [comment]
این ایشو برای بررسی منتقل شد. فعلا بسته میشود
