### ISSUE TITLE
مشکل Post در API

### ISSUE THREAD

**Issue by Rasoul-Khajavi** [hiddify/Hiddify-Server#3311]
در آخرین ورژن در نسخه رلیز و دودلوپر وقتی به
https://site.com/proxy_path/admin_key/api/v1/user/
پست میزنم این ارور میگیرم 
{"message": "The browser (or proxy) sent a request that this server could not understand."}
 محتوبات پست هم طبق مستندات هست : 
{
"uuid": "6ebd2ea8-4d41-48b7-8fc2-7d6570da30a9",
"name": "Test",
"added_by_uuid": "abb4bdb8-732c-4fa6-92e0-6b3fd4bb8450",
"current_usage_GB": 0,
"usage_limit_GB": 1,
"package_days": 900,
"start_date": null,
"comment": null,
"last_online": "1-01-01 00:00:00",
"last_reset_time": "2023-05-21",
"mode": "no_reset",
"telegram_id": null
}

اینم بگم که get مشکلی نداره طبق مستندات و جواب میگیرم از api

**Comment by lymanjre** [comment]
این مورد جهت بررسی منتقل میشود. ایشو فعلا بسته میشود
