### ISSUE TITLE
مشکل ایجاد دامنه

### ISSUE THREAD

**Issue by Ali-dy7** [hiddify/Hiddify-Server#3313]
با سلام 
مشکل در ایجاد دامنه وجود دارد که ارور ۵۰۰ میدهد که به اخرین نسخه تبدیل شود که اپدیت انجام شد اپلای هم انجام شد و حتی ریستارت هم انجام دادم ولی باز مشکل پابرجاست.

**Comment by lymanjre** [comment]
بله این ایشو توسط دوست دیگری هم ثبت شده و در دست پیگیری است. ایشو شما بسته میشود
