### ISSUE TITLE
پنل آپدیت نمیشود

### ISSUE THREAD

**Issue by alirezarah** [hiddify/Hiddify-Server#3320]
با سلام و تشکر از زحمات شما
وقتی که ورژن پنل قدیدمی میشه و اخطار " این نسخه هیدیفای قدیمی شده است. لطفا از پنل ادمین آن را به روزرسانی کنید " میده چه از طریق بروزرسانی خود پل و یا از طریق منو ssh برای آپدیت و یا با دستور sudo bash update.sh انجام دادم میاد که پنل اپدیت شده به ورژن جدید کارهایی انجام میشه ولی پنل بر روی همون ورژن قدیمی هست و آپدیت به ورژن جدید نمیشه

**Comment by lymanjre** [comment]
آپدیت جدید را نصب کنید مشکل حل شده
