### ISSUE TITLE
پینگ بسیار بالا

### ISSUE THREAD

**Issue by Ali-dy7** [hiddify/Hiddify-Server#3323]
با عرض سلام و خسته نباشید خدمت دوستان و زحمتکشان هیدیفای
یه مشکلی برای من پیش اومده من قبل از نصب پنل از سیستم خودم وقتی پینگ سرورمو میگرفتم پینگم اوکی بود ولی بعد از نصب و انجام کارها کانفینگامو که متصل میشم بهشون تروجان و ویلس ها کار میکنن اما پینگ خیلییی بالا و اینکه دیگه از سیستم خودم به ای پی سرورم پینگ ندارم همش تایم اوت دارم این درحالیه که کانفینگام با پینگ خیلی بالا دارن کار میکنن لطفا راهنمایی کنید چه کاری باید انجام بدم
دیتاسنتر هتزتر هستش

**Comment by lymanjre** [comment]
فایروال روشن میشه توسط هیدیفای برای امنیت بیشتر. توی ویکی مطلب فایروال را بخونید متوجه میشید
