### ISSUE TITLE
وارپ و اف شدن سرور

### ISSUE THREAD

**Issue by nojhanac** [hiddify/Hiddify-Server#3324]
سلام هرکاری میکنم ای پی نمیره پشت کلود مخفی بشه  در ورژن هفت میشد ولی این ورژن هشت به بعد نمیشه
ورژن ۸.۶.۷
هروز سرورم اف میشه و باید از پنل سرور یکبار ریست کنم 
و هربار هم که این مشکل رخ بده سرچ گوگل ندارم 
یبار باید ریلز رو اپدیت کنم تا وارپ درست بشه

**Comment by FarshadFaramarzlou** [comment]
منم این مشکل رو دارم!

**Comment by Lenjerman2022** [comment]
منم همینطور کلا مخفی نمیشه

**Comment by lymanjre** [comment]
کد وارپ معتبر استفاده نمایید
