### ISSUE TITLE
erorr panel 8.6.8

### ISSUE THREAD

**Issue by alirezarah** [hiddify/Hiddify-Server#3328]
سلام
هیدیفای رو که نصب میکنی اخرش این پیغام خطا رو میده و اصلا آدرسی رو که میده باز نمیکنه
![Untitled](https://github.com/hiddify/Hiddify-Server/assets/116164916/fbaba625-dcae-4c06-a626-3417413a466c)

**Comment by Lenjerman2022** [comment]
باگه کلا پنل ب باگ خورده

**Comment by lymanjre** [comment]
ایشو جهت بررسی منتقل شد. ایشو شما فعلا بسته میشود

**Comment by ramindoroozeh** [comment]
حل نشد؟
