### ISSUE TITLE
مهم

### ISSUE THREAD

**Issue by Lenjerman2022** [hiddify/Hiddify-Server#3329]
این چ گروه   تلگرامیه ک دارید با ادمین هاتون همه ادمین های شما جوری برخود میکنن ک انگار با ما دشمنی دارن هر سوالیم ک میکنیم جواب نمیدن و با جواب های  تکراری ادمو بن میکنن از گروه اگ بچه های هیدیفای اینقدر عصبی و تند برخورد میکنن خب چرا گروه رفع اشکال گذاشتید لطف کنید گروه رو پاک کنید یکم ادب یکم احترام تو این گپ های شما نیست همه ادمین هاتون فقط بن کردن کاربر ها رو بلدن 
  جوابدهی ب مشکلات پنل و نصب پنل یعنی صفره بازم از اون دسته از ادمین هایی ک با صبوری و احترام مشکلات رو رفع میکنن تشکر میکنم

**Comment by Sysop0098** [comment]
متاسفانه گروه اینقد شلوغه که هیچ توجهی به سوالات نمیکنن
