### ISSUE TITLE
آپدیت نشدن پنل هیدیفای

### ISSUE THREAD

**Issue by alirezarah** [hiddify/Hiddify-Server#3330]
با سلام و خسته نباشید
ورژن پنل هیدیفای من 8.0.3 هست و پیغام میده که " ⚠️ این نسخه هیدیفای قدیمی شده است. لطفا از پنل ادمین آن را به روزرسانی کنید " من هرچی از طریق پنل ادمین به روزرسانی میزنم و چه از منو ssh اپدیت به نسخه release رو میزنم و یا با دستور sudo bash update.sh میزنم دستورات اجرا میشه ولی به ورژن بالاتر آپدیت نمیشه ولی قبلا میزنم اپدیت میشد.

**Comment by amin2plus** [comment]
منم این مشکل رو دارم ، ورژن پنل روی 8.6.6 گیر کرده ، دستی هم اپدیت میزنم توی لاگ میزنه که آپدیت شد به 8.6.10 ولی ورژنی که توی وب پنل نمایش داده میشه همون 8.6.6 نمایش داده میشه، توی لاگز هیچ ارور خاصی هم نشون نمیده

**Comment by hiddify-com** [comment]
لطفا این دستور را در ssh سرورتون اجرا کنید
```
sudo rm -rf /usr/lib/python3/dist-packages/OpenSSL
sudo pip3 install pyopenssl
sudo pip3 install pyopenssl --upgrade
echo "nameserver 1.1.1.1" >/etc/resolv.conf  &&sysctl -w net.ipv6.conf.all.disable_ipv6=1 &&/opt/hiddify-config/update.sh release 
```

**Comment by Barzegari-mohammad** [comment]
![image](https://github.com/hiddify/Hiddify-Manager/assets/161923392/cc42dd1a-172e-441b-98f3-53428cba6460)
این موراد رو زدم ولی بازم این خطا رو میده

**Comment by Barzegari-mohammad** [comment]
> لطفا این دستور را در ssh سرورتون اجرا کنید
> 
> ```
> sudo rm -rf /usr/lib/python3/dist-packages/OpenSSL
> sudo pip3 install pyopenssl
> sudo pip3 install pyopenssl --upgrade
> echo "nameserver 1.1.1.1" >/etc/resolv.conf  &&sysctl -w net.ipv6.conf.all.disable_ipv6=1 &&/opt/hiddify-config/update.sh release 
> ```

![image](https://github.com/hiddify/Hiddify-Manager/assets/161923392/36110c02-f4a3-42ab-9369-83bcf7f9d4cc)
این موراد که فرمودین را زدم ولی باز این ارور را میده
