### ISSUE TITLE
آپدیت نشدن پنل 8.0.3

### ISSUE THREAD

**Issue by alirezarah** [hiddify/Hiddify-Server#3332]
با سلام و خسته نباشید ورژن پنل من 8.0.3 هست من دستوراتی که دادین رو زدم ولی بازم آپدیت نشد

sudo rm -rf /usr/lib/python3/dist-packages/OpenSSL
sudo pip3 install pyopenssl
sudo pip3 install pyopenssl --upgrade
echo "nameserver 1.1.1.1" >/etc/resolv.conf  &&sysctl -w net.ipv6.conf.all.disable_ipv6=1 &&/opt/hiddify-config/update.sh release 

همون ورژن قبلیه

**Comment by hiddify-com** [comment]
توی گروه t.me/hiddify_board بپرسید دوستان کمکتون کنند

**Comment by alirezarah** [comment]
سئوال کردم کسی جواب نداد

**Comment by amin2plus** [comment]
> سئوال کردم کسی جواب نداد

اول خروجی بک آپ رو از پنل هیدیفای دانلود کن، توی پنل هاستت بزنن مجدد سیستم عامل رو برات نصب کنند (معمولا رایگان هست) reinstall OS
حدودا 90% هاست ها خودکار برات اوکی میکنند و چند دقیقه بیشتر طول نمیکشه ، (بعضی هاست ها هم هستند که صرفا یه image نصب رو mount  میکنن و خودت باید سیستم عامل رو نصب کنی که کاری نداره و توی یوتوب کلی ویدیوو هست)
سیستم عامل که بالا امد یه `sudo su&&apt update&&apt full-upgrade -y&&apt autoremove -y&&reboot now` بزن و بعد اسکریپت نصب هیدیفای رو اجرا کن، پنل که بالا امد مستقیم برو توی قسمت بک آپ و فایل بک آپی رو بده و بزن تنظیمات؛کاربرا و دامین ها برگردند
کلا 15 دقیقه طول میکشه همه اینا، اگه کاربر زیاد داری یه شب دیر وقت یا صبح خیلی زود بزن کسی متوجه نمیشه، لینک کاربرا هم تغییر نمیکنه
