### ISSUE TITLE
امکان تغییر دی ان اس سرور

### ISSUE THREAD

**Issue by amirhosseinf79** [hiddify/Hiddify-Server#393]
سلام یه پیشنهاد دارم برای پنل
به نظرم یه تنظیمات برای dns سرور هم بذارید که بتونیم از بین چند تا dns provider یکی رو انتخاب کنیم.
مثلا:
دی ان اس گوگل 8.8.8.8
1.1.1.1
دی ان اس یاندکس (مخصوصا اینو میگن خوب جواب میده)
یا حتی امکان وارد کردن دی ان اس شخصی

**Comment by realartin** [comment]
موافقم شدیدا بهش نیازه
