### ISSUE TITLE
مشکل با اینستاگرام

### ISSUE THREAD

**Issue by mfoolady** [hiddify/Hiddify-Server#659]
سلام.
چند روزی هست که دارم هیدیفای رو تست میکنم و همه چیز عالی هست. خدا قوت به تیم توسعه دهنده و دمتون گرم.

فقط به شدت با اینستاگرام مشکل دارم یعنی وقتی پروکسی فعال میشه همه چیز اوکیه مثلا سایت های فیلتر شده یا تلگرام و ... خیلی عالی کار میکنند ولی پستهای اینستا گرام لود نمیشه. هر مدل تنظیم و کانفیگی رو هم که بگید تست کردم(fake, direct,cdn,auto,...)
نمیدونم که چی کار کنم.

**Comment by DoodleKhan** [comment]
درسته . بعد از اپدیت مدام اینستا وسط ویدیو وای میسه. با وی پی ان دیگه همه جی اوکی هست
