### ISSUE TITLE
Get 502 error on get_some_random_reality_friendly_domain

### ISSUE THREAD

**Issue by AliGh1** [hiddify/Hiddify-Server#776]
**Describe the bug**
سلام, روزتون بخیر 
در قسمت تنظیمات ریلیتی اون لینک برسی و پیشنهاد دامنه خطای 502 Bad Gateway میده
و یه نکته ای که هست برای دامنه بازگشتی اجازه نمیده از یه چننین فرمتی استفاده بشه مثل www.google.com:443

**Comment by zekerya** [comment]
برای من هم 502 میاره. ورژن 4.3.1
