### ISSUE TITLE
SSL Problem

### ISSUE THREAD

**Issue by ea1234567** [hiddify/Hiddify-Server#796]
من تا ورژن قبلی هیچ مشکلی نداشتم
ولی ورژن جدید پنل رو که از اول نصب میکنم
همون اول کار که وارد پنل میشم میگه یه دامین وارد کن،دامین رو که میزنم دیگه برای دامین ssl دریافت نمیکنه
و مجبور میشم با آی پی فقط وارد پنل بشم

**Comment by mk379** [comment]
منم دقیقا به همین مشکل بر خوردم.
