### ISSUE TITLE
مشکل بازگرداندن بکاپ

### ISSUE THREAD

**Issue by Maco661** [hiddify/Hiddify-Server#800]
سلام من یه بکاپ از پنل هیدیفای گرفتم الان پنل و رو یه سرور دیگه ریختم ولی بکاپ و کاربرا بر نمیگردن رو سرور دیگه فقط میخوام کاربرا بیان اینور و تنظیمات ایناش و نزاشتم تو بازیابی. میشه راهنمایی کنید چیکار کنم؟

**Comment by TsTeam2** [comment]
دقیقا منم همین مشکلو دارم در حالی که تمامی تنظیماتم درست هستش
و روی چندین سرور تست کردم مشکل همچنان هستش

**Comment by vforv54** [comment]
منم همین مشکل دارم بکاپ گرفتن آوردم تو سرور جدید دامنه و تنظیمات درست شدن ولی کاربر ها بر نگشتن
