### ISSUE TITLE
مشکل عدم دسترسی به سرور بعد از اتصال به جیکور

### ISSUE THREAD

**Issue by mska22** [hiddify/Hiddify-Server#922]
برای دومین بار روی یه سرور وقتی می خوام از cdn شرکت gcore استفاده کنم یه دفعه دسترسی قطع می شه و کلا دیگه به سرور نمی شه دسترسی داشت
هر دوی سرور ها سرور جدید بودن و ipهاشون تمیز بوده وقبل از نصب پنل تو چک هاست tcp و udp و ping و ایناشون و تست کردم
بعد از تلاش برای گرفتن ssl دسترسی به سرور قطع می شه حتا ssh هم نمی شه زد به سرور
نه ریست و حتا نصب دوباره هم کمکی نمی کنه
تاوقتی به جیکور وصل باشه همینه
فقط  زمانی که cdn جیکور و حذف می کنم درست می شه
دقیقا مطابق آموزش جیکور پیش رفتم و رو هر دو سرور همین مشکل پیش اومد.
ممنون از زحماتی که می کشین

**Comment by sepahdalton** [comment]
> برای دومین بار روی یه سرور وقتی می خوام از cdn شرکت gcore استفاده کنم یه دفعه دسترسی قطع می شه و کلا دیگه به سرور نمی شه دسترسی داشت هر دوی سرور ها سرور جدید بودن و ipهاشون تمیز بوده وقبل از نصب پنل تو چک هاست tcp و udp و ping و ایناشون و تست کردم بعد از تلاش برای گرفتن ssl دسترسی به سرور قطع می شه حتا ssh هم نمی شه زد به سرور نه ریست و حتا نصب دوباره هم کمکی نمی کنه تاوقتی به جیکور وصل باشه همینه فقط زمانی که cdn جیکور و حذف می کنم درست می شه دقیقا مطابق آموزش جیکور پیش رفتم و رو هر دو سرور همین مشکل پیش اومد. ممنون از زحماتی که می کشین

عزیز دل شما اشتباه پیکربندی میکنی
ابتدا دامنه رو بصورت دایرکت ادد کن و اپلی کانفینگ بزن بعد که ssl دریافت شد و موفق شدی با دامنه جدید پنل رو بالا بیاری  اونوقت توی gcore پروکسی رو روشن کن و داخل پنل روی حالت cdn بزار و اپلی کانفینگ کن قطعا مشکلت حل میشه

**Comment by mska22** [comment]
ممنون بابت راهنمایی
برای روشن کردن پروکسی تو gcore باید بذارم روی https? همین کافیه؟

**Comment by sepahdalton** [comment]
بله همون کافیه
عزیز دل اینجا جای راهنمایی نیست اینجا محل گزارش باگ و ایده اس 
شما مشکلتو میتونیستی توی گروه تلگرامی بگی و سریعتر حل بشه
سوالی داشتی 
eth2btc
ایدی تلگرام
موفق باشی
