### ISSUE TITLE
تا فرصت باقی هست روند کاری‌تان را عوض کنید

### ISSUE THREAD

**Issue by robin98** [hiddify/Hiddify-Server#926]
اکثر ما فرهنگ بد و مخربی داریم که سر هر مساله بسیار احساسی و مدیریت نشده کار می کنیم.
همین باعث میشه که در هیچکاری سازماندهی نداشته باشیم و ساماندهی کار از دست ما خارج بشه.
در واقع جوری هستیم که در ابتدای مساله، بسیار احساسی و تند و آتشین جلو میریم و تمام انرژی خود را در ابتدای کار تمام می کنیم، در نتیجه در اواسط مسیر، از ادامه کار باز میمونیم.

من از نسخه 1 هیدیفای به شکل قابل توجهی روی این پروژه فوکوس داشتم (به عنوان یک مصرف کننده و بررسی کننده) و تا امروز هم همینطور بوده.
باید اعلام کنم پروژه داره با سرعت زیادی به سمت بیراهه و درهم تنیده شدن میره (مثالی که برنامه نویس ها استفاده می کنند: اسپاگتی کد)

> 
> باگ های پی در پی و مهلک
> ناپایداری غیرقابل تحمل در محصول
> عدم داشتن یک چارت روشن و مناسب برای توسعه محصول و هر-دم-میلی جلو رفتن
> عدم تمرکز و قدرت کافی برای ساماندهی قابلیت های موجود، و حرکت سراسیمه و بی برنامه از روی ذوق و هیجان به سمت فیچر های جدید و نیمه تمام رها کردن آنها ..... (ادامه و ادامه این روند الی آخر...)

به عنوان یک مصرف کننده دیگر به این پروژه نمی توانم اعتماد داشته باشم چونکه در یک محیط کوچک غیرپروداکشن، در این اواخر اعتماد من به شدت به چالش کشیده شد و استفاده از پنل های دیگر و ساده مبتنی بر x-ui را چاره کار خود می بینم.

### اگر میخواهید این پروژه نجات پیدا کند خوب به توضیحات زیر توجه کنید:

> تعیین یک الی 3 فرد برای نظارت و مدیریت دقیق روی روند اجرایی
> مسدود کردن گروه تلگرامی/مسدود کردن بخش درخواست فیچر در گیتهاب و ... (پشتیبانی کاربران وظیفه شما نیست، اما می توانید از کارکرد صحیح محصول خود از طریق کانال های مطمئن و فیدبک از افراد متخصص مطمئن شوید، اما لطفا لطفا لطفا دیگر با end-user های از همه جا بی خبر مستقیما در ارتباط نباشید چونکه نقشه ذهنی شما را به هم می زند) از اینکار خجالت نکشید و فورا اینکار را انجام بدید. در ارتباط بودن با این حجم از یوزرها  فقط وقت شما را تلف می کنه. ممکنه که در ابتدا باعث خوشحالی باشه یا فکر کنید اینطوری ایده های بیشتری دریافت می کنید، اما همین پاشنه آشیل هست که در انتها باعث فروپاشی پروژه ها میشه
> کنار گذاشتن توسعه های جاه طلبانه و غیربالغانه و تمرکز کردن روی فیکس باگ های اساسی فعلی (به طور مثال من امشب 3 دفعه پایگاه داده را از دست دادم و 4 مرتبه هم سرویس انجینکس استاپ شد و هر بار هم کلین اینستال سیستم عامل کردم ولی نتیجه صفر!)
> تعیین یک فرد با سابقه و کارکشته در حوزه دواپس، ترجیحا بالای 40 سال و ترجیحا خارج از ایران به عنوان ناظر روی تکنولوژی ها (مثلا پایگاه داده و ترکیب سرویس های مختلف پروژه) تا بدین صورت به شکل هیجانی و ملق وار بین چپ و راست در حال دویدن نباشید و آن شخص به شما کمک کند تا از استیبل ترین و بهترین مسیر ممکن، به سرعت کارها را پیش ببرید.
> 

اینها یک تمرین خوب است برای اینکه در آینده در فیلد خودتان حرفی برای گفتن داشته باشید، اما اگر بخواهید اینگونه با خرابکاری روی سیستم های مردم و عدم مسئولیت پذیری به تمرین بپردازید و به دنبال کسب تجربه باشید، نه خودتان فایده ای می برید، نه مردم فایده ای می برند و در کل فاتحه ما خوانده شد رفت.

_اگر کار نظام و سامان داشت و بر روی اساس یک دیسیپلین صحیح جلو میرفت، وجود حتی یک باگ جزئی هم جای تعجب داشت._
حالا همه ایشو ها رو دیلیت کنید، گروه رو ببندید، برای 72 ساعت به مرخصی مطلق برید و بعد از 3 روز بیایید ببینید این سیستم چه مرگشه.
تا اون موقع آپدیت رول بک کنید روی اولین نسخه ای که ریالیتی پایدار شده بود.

**Comment by vafaaee** [comment]
با اینکه با بخش زیادی از صحبت شما موافق نیستم و احساس میکنم کمی تند رفتید و اینطور نگاه کردن کمی هم بی انصافی به بچهای پروژه هست، اما در اون قسمت که گفتید ارتباط با end-user برای پروژه مخرب هست رو بسیار موافقم، چون بخش زیادی از انرژی تیم صرف بررسی چیزهایی میشه که در خیلی از موارد نه تنها به نفع پروژه نیست بلکه مخربه.
و در مورد آپدیت هم دوستان باید چندتا ریپازیتوری بر مبنای نسخه ها ایجاد کنن و این امکان رو بذارن که هر کسی نسخه دلخواهش رو نصب کنه، اینطوری هم افرادی که مثل شما دنبال نسخه استیبل هستن کمتر دچار مشکل میشن و هم افرادی مثل من که مدام در حال تست نسخه جدید هستن 🤦‍♂️

**Comment by amin1363** [comment]
یک سری داوطلب با استعداد لطف میکنن با توجه به شرایط وحشتناک اینترنت ایران رو این پروژه فوق العاده کار میکنن اونوقت تو مگه طلبکاری که با این لحن از بالا به پایین مثل یک مدیر پروژه یا مدیر عامل حرف میزنی؟؟یک قرون پول تا حالا کمک کردی؟؟ تو فقط یه یوزر ساده ای و هرچی دادن بهت باید تشکر کنی یا اگه ناراحتی بری پروژه خودتو بنویسی...

**Comment by robin98** [comment]
@vafaaee 
بله شما هم درست می فرمایید بالاخره این روند رو هم نمیشه ادامه داد و باید فکری براش کرد. در ضمن همین الان دوتا برنچ مختلف به اسم ریلیز و دولوپ وجود داره، اما بعد از مدت ها متوجه نمیشم چرا قیمه ها دائما میریزه داخل ماستا؟ تازه این رو بگم که کار به جایی رسید که مجبور شدم تیک اتوآپدیت رو بردارم و این مدت هم بخاطر ریالیتی مجبور شدم چندبار دستی آپدیت کنم که تازه اونهم به خاطر یه سری استاندارد های من درآوردی هیدیفای هزارجور مشکل و محدودیت داشت.
 @amin1363 
با این حرف شما هم مخالفم، بخش اول حرفتون داره به من میگه که خودم چه مشارکتی کردم، که من سعی کردم با متنی که بالا نوشتم مشارکتمو انجام بدم و به قول شما با یک مدیریت از بالا به پایین و ایجاد یه دیسیپلین، این اوضاع بهم ریخته رو سامان بدم.
حالا من سوادم در همین حده، اونکسی هم که برنامه نویسی بلده میره دوخط کدمیزنه مشارکت میکنه و اونکسی هم که شبکه بلده میره کار خودشو می کنه... 
بخش دوم حرفتون هم یاد زینب در صدا و سیما افتادم که میگفت هرکی ناراحته جمع کنه بره.

اگه هم از لحاظ فنی یا مدیریتی نظری دارید خوشحال میشیم که بشنویم
ولی اینکه باز برم و بیام هفته دیگه هم صدتا ریکوئست از طرف عزیزان فروشنده و end-user اینجا باشه که دارن خرده فرمایشات میکنن و یه پروژه با پتانسیل بالا رو تبدیل به باتلاقی از هزاران فیچر نیمه کاره و پر از باگ میکنن.... اون موقع یعنی هیدیفای دیگه از دست رفت.

یوزر نهایی یا عوامل فروش که درک این رو ندارن و تا جایی که بتونن درخواست فیچر میدن، من روی حرفم با کسایی هست که دارن روی پروژه مشارکت میکنن و اونها رو دعوت به این می کنم که دیسیپلین پیشه کنن و به فکر راهکار های موثر، منعطف و بروز باشن.

**Comment by sepahdalton** [comment]
> اکثر ما فرهنگ بد و مخربی داریم که سر هر مساله بسیار احساسی و مدیریت نشده کار می کنیم. همین باعث میشه که در هیچکاری سازماندهی نداشته باشیم و ساماندهی کار از دست ما خارج بشه. در واقع جوری هستیم که در ابتدای مساله، بسیار احساسی و تند و آتشین جلو میریم و تمام انرژی خود را در ابتدای کار تمام می کنیم، در نتیجه در اواسط مسیر، از ادامه کار باز میمونیم.
> 
> من از نسخه 1 هیدیفای به شکل قابل توجهی روی این پروژه فوکوس داشتم (به عنوان یک مصرف کننده و بررسی کننده) و تا امروز هم همینطور بوده. باید اعلام کنم پروژه داره با سرعت زیادی به سمت بیراهه و درهم تنیده شدن میره (مثالی که برنامه نویس ها استفاده می کنند: اسپاگتی کد)
> 
> > باگ های پی در پی و مهلک
> > ناپایداری غیرقابل تحمل در محصول
> > عدم داشتن یک چارت روشن و مناسب برای توسعه محصول و هر-دم-میلی جلو رفتن
> > عدم تمرکز و قدرت کافی برای ساماندهی قابلیت های موجود، و حرکت سراسیمه و بی برنامه از روی ذوق و هیجان به سمت فیچر های جدید و نیمه تمام رها کردن آنها ..... (ادامه و ادامه این روند الی آخر...)
> 
> به عنوان یک مصرف کننده دیگر به این پروژه نمی توانم اعتماد داشته باشم چونکه در یک محیط کوچک غیرپروداکشن، در این اواخر اعتماد من به شدت به چالش کشیده شد و استفاده از پنل های دیگر و ساده مبتنی بر x-ui را چاره کار خود می بینم.
> 
> ### اگر میخواهید این پروژه نجات پیدا کند خوب به توضیحات زیر توجه کنید:
> > تعیین یک الی 3 فرد برای نظارت و مدیریت دقیق روی روند اجرایی
> > مسدود کردن گروه تلگرامی/مسدود کردن بخش درخواست فیچر در گیتهاب و ... (پشتیبانی کاربران وظیفه شما نیست، اما می توانید از کارکرد صحیح محصول خود از طریق کانال های مطمئن و فیدبک از افراد متخصص مطمئن شوید، اما لطفا لطفا لطفا دیگر با end-user های از همه جا بی خبر مستقیما در ارتباط نباشید چونکه نقشه ذهنی شما را به هم می زند) از اینکار خجالت نکشید و فورا اینکار را انجام بدید. در ارتباط بودن با این حجم از یوزرها  فقط وقت شما را تلف می کنه. ممکنه که در ابتدا باعث خوشحالی باشه یا فکر کنید اینطوری ایده های بیشتری دریافت می کنید، اما همین پاشنه آشیل هست که در انتها باعث فروپاشی پروژه ها میشه
> > کنار گذاشتن توسعه های جاه طلبانه و غیربالغانه و تمرکز کردن روی فیکس باگ های اساسی فعلی (به طور مثال من امشب 3 دفعه پایگاه داده را از دست دادم و 4 مرتبه هم سرویس انجینکس استاپ شد و هر بار هم کلین اینستال سیستم عامل کردم ولی نتیجه صفر!)
> > تعیین یک فرد با سابقه و کارکشته در حوزه دواپس، ترجیحا بالای 40 سال و ترجیحا خارج از ایران به عنوان ناظر روی تکنولوژی ها (مثلا پایگاه داده و ترکیب سرویس های مختلف پروژه) تا بدین صورت به شکل هیجانی و ملق وار بین چپ و راست در حال دویدن نباشید و آن شخص به شما کمک کند تا از استیبل ترین و بهترین مسیر ممکن، به سرعت کارها را پیش ببرید.
> 
> اینها یک تمرین خوب است برای اینکه در آینده در فیلد خودتان حرفی برای گفتن داشته باشید، اما اگر بخواهید اینگونه با خرابکاری روی سیستم های مردم و عدم مسئولیت پذیری به تمرین بپردازید و به دنبال کسب تجربه باشید، نه خودتان فایده ای می برید، نه مردم فایده ای می برند و در کل فاتحه ما خوانده شد رفت.
> 
> _اگر کار نظام و سامان داشت و بر روی اساس یک دیسیپلین صحیح جلو میرفت، وجود حتی یک باگ جزئی هم جای تعجب داشت._ حالا همه ایشو ها رو دیلیت کنید، گروه رو ببندید، برای 72 ساعت به مرخصی مطلق برید و بعد از 3 روز بیایید ببینید این سیستم چه مرگشه. تا اون موقع آپدیت رول بک کنید روی اولین نسخه ای که ریالیتی پایدار شده بود.

این چه مذخرفاتیه میگی معلومه سوادت صفره و یه جیره خوری که فقط قصدت تخریبه
پروژه اوپن سورسه میفهمی معنی اینو یا نه؟
توی هراپدیتی که ارائه شده واقعا کلی زحمت کشیده شده و من بشخصه مشکل شمارو هیچ وقت نداشتم و اتفاقا برعکس کیفیت کانکشنا بهتر شده
پروژه ای که از اساس رایگانه و داره هرروز اپدیت میشه رو شما حق نداری اینجوری با این لحن تند نابود کنی خجالت بکش 
بجای گفتن این چرت و پرتا ایده خوب بده یا گزارش خطا بده با مدرک درست حسابی رو هوا فقط حرف میزنی
من از نسخه ۳ تا نسخه ۶ واقعا کیفیت کانکشن هام بهتر شده و هیچ وقتم مشکل شمارو نداشتم 
دراخر بگم اپدیت ها دونسخه رلیز و دولوپ دارن که مشخصه هدف چیه شما اول برو ببین اصن پنلو درست نصب و پیکربندی بکن بعد بیا این حرفا رو بزن
ایدی تلگرام بنده
eth2btc
پیام بده تا واست نصب وکانفینگ کنم با روش درست ببینم بازم این چرتو پرتا رو میگی
بچه های گل هیدفای میدونم نقدپذیر هستید دمتون گرم ولی حرفای این بیسواد رو ندید بگیرید
باتشکر از تیم حرفه ای و بامرام هیدفای💗💗

**Comment by realartin** [comment]
99%
داری اشتباه میزنی اخوی

**Comment by stm32learn** [comment]
منم تمام این مشکلات رو داشتم
اینستالر کار نمیکرد
سرعت اتصال کمتر میشد(عحیب ولی واقعی)
کل هیدیفای میپرید و فقط با کلین اینستال حل میشد
هیچی مثل x-ui بیس ها نیست
مدتی دارم از x-ui alirezao استفاده میکنم
سرعت خوب
امنیت خوب
بهینه در مصرف منابع
فیچر های خوب
