### ISSUE TITLE
مشکل غیر فعال شدن haproxy

### ISSUE THREAD

**Issue by amirakrami852** [hiddify/Hiddify-Server#999]
سلام و خسته نباشید الان چهار شب پشت سر هم هستش که ساعت ۱۲:۵۵ haproxy پنل من خود به خود غیر فعال میشه و بعد reinstall کردن دوباره پنل کار میکنه یه عکس هم ضمیمه کردم که لاگ ارور هست فکر کنم 
![Uploading IMG_2677.jpeg…]()

**Comment by amirakrami852** [comment]
![IMG_2677](https://user-images.githubusercontent.com/124598649/236765797-06e7f7bc-2352-4f46-8770-574fddf3280f.jpeg)

**Comment by The-Mj-01** [comment]
برای من هم هر شب راس ساعت 12:37 دقیقه این اتفاق می افته.
اینکه هر شب مجدد استارتش کنی هم راه حل مشکل نیست.
